---
- name: Install RPM packages
  dnf:
    name:
      - git
      - vim
      - freeipa-server
    state: present

- name: install freeipa server
  shell: ipa-server-install -a adminPassw0rd! --hostname=ipa.example.test -r EXAMPLE.TEST -p adminPassw0rd! -n example.test -U
  args:
    creates: /var/lib/ipa/sysrestore/sysrestore.state

- name: get freeipa-fas
  git:
    repo: https://github.com/fedora-infra/freeipa-fas.git
    dest: /root/freeipa-fas

- name: install freeipa-fas
  shell: ./install.sh
  args:
    chdir: /root/freeipa-fas/
    creates: /usr/share/ipa/updates/99-fas.update
