version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: cryptography
    versions:
    - 3.4.4
    - 3.4.5
  - dependency-name: flake8
    versions:
    - 3.8.4
  - dependency-name: pytest
    versions:
    - 5.4.3
