pull_request_rules:

- name: Automatic merge on approval
  actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/authdev
  - "#approved-reviews-by>=1"
  - status-success=DCO
  - status-success=CI on f33
  - status-success=CI on f34

- name: Automatic merge Dependabot PRs
  actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - author=dependabot[bot]
  - approved-reviews-by=github-actions[bot]
  - status-success=DCO
  - status-success=CI on f33
  - status-success=CI on f34
