queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Checks
      - status-success=Licenses
      - status-success=Documentation
      - status-success=Unit tests (py39)
      - status-success=Unit tests (py310)

pull_request_rules:

  - name: Merge on approval
    actions:
      queue:
        name: default
        method: rebase
    conditions:
      - label!=WIP
      - -draft
      - approved-reviews-by=@fedora-infra/authdev
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Checks
      - status-success=Licenses
      - status-success=Documentation
      - status-success=Unit tests (py39)
      - status-success=Unit tests (py310)
