# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

name: Apply labels when deployed

on:
  push:
    branches:
      - staging
      - stable

jobs:
  label:
    name: Apply labels
    runs-on: ubuntu-latest

    steps:
      - name: Staging deployment
        uses: fedora-infra/label-when-in-branch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          label: deployed:staging
      - name: Production deployment
        uses: fedora-infra/label-when-in-branch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: stable
          label: deployed:prod
